### ISSUE TITLE
góp ý về phân vùng ổ cứng cho hướng dẫn cài đặt arch

### ISSUE THREAD

**Issue by hahahahacker2009** [p3nguin-kun/blogs#1]
Nên tạo các phân vùng riêng rẽ: 1G cho /, nếu thích thì 500M cho /boot không thì thôi, cần có phân vùng cho /usr, /var, nếu dùng /opt thì tạo phân vùng cho /opt, /usr/local cũng nên tạo dù để nhỏ thôi vì linux ko dùng tới; tạo phân vùng cho /home, chắc bạn nhiều ram rồi thì /tmp dùng tmpfs, nếu ít ram thì cũng lại tạo một phân vùng

tạo thêm phân vùng chả phí gì, lại vừa có thể mở ra với các tùy chọn như nodev, nosuid, noexec vào /var, nodev, nosuid cho /home, /tmp, v.v. Không chỉ vậy giảm thiểu rủi ro hỏng dữ liệu, chạy mkfs và fsck nhanh hơn.

Đối với bios chắc là tạo phân vùng bằng lvm (mình chưa dùng bao giờ)

Về kích thước các phân vùng thì tham khảo https://man.openbsd.org/disklabel.8#AUTOMATIC_DISK_ALLOCATION

**Comment by p3nguin-kun** [comment]
oat???

**Comment by p3nguin-kun** [comment]
phân vùng cho từng dir khá mệt, nên tôi k muốn setup kiểu v

**Comment by hahahahacker2009** [comment]
:)
dùng linux mà như dùng windows ấy
bọn ms lại chả thèm cái removable fs ấy quá
